apiVersion: apps/v1
kind: Deployment
metadata: 
  name: tickets-payments-deploy
spec: 
  replicas: 1
  selector:
     matchLabels:
        app: tickets-payments
  template:
     metadata:
        labels:
           app: tickets-payments
     spec:
        containers:
          - name : tickets-payments
            image: luiskalo95/tickets-payments
            env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://tickets-nats-service:4222'   
            - name: NATS_CLUSTER_ID
              value: ticketing  
            - name: MONGO_URI
              value: 'mongodb://tickets-payments-mongo-service-cip:27017/payments'
            - name: JWT_KEY
              valueFrom: 
                 secretKeyRef:
                   name: jwt-secret
                   key: JWT_KEY
            - name: STRIPE_KEY
              valueFrom:
                 secretKeyRef:
                    name: stripe-secret
                    key: STRIPE_KEY
---
apiVersion: v1
kind: Service
metadata: 
  name: tickets-payments-service-cip
spec:
  selector:
    app: tickets-payments
  ports:
    - name: tickets-payments
      protocol: TCP
      port: 3000
      targetPort: 3000
