apiVersion: apps/v1
kind: Deployment
metadata: 
  name: tickets-orders-deploy
spec: 
  replicas: 1
  selector:
     matchLabels:
        app: tickets-orders
  template:
     metadata:
        labels:
           app: tickets-orders
     spec:
        containers:
          - name : tickets-orders
            image: luiskalo95/tickets-orders
            env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://tickets-nats-service:4222'   
            - name: NATS_CLUSTER_ID
              value: ticketing  
            - name: MONGO_URI
              value: 'mongodb://tickets-orders-mongo-service-cip:27017/orders'
            - name: JWT_KEY
              valueFrom: 
                 secretKeyRef:
                   name: jwt-secret
                   key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata: 
  name: tickets-orders-service-cip
spec:
  selector:
    app: tickets-orders
  ports:
    - name: tickets-orders
      protocol: TCP
      port: 3000
      targetPort: 3000
