apiVersion: apps/v1
kind: Deployment
metadata: 
  name: tickets-client-deploy
spec: 
  replicas: 1
  selector:
     matchLabels:
        app: client
  template:
     metadata:
        labels:
           app: client
     spec:
        containers:
          - name : client
            image: luiskalo95/tickets-client
---
apiVersion: v1
kind: Service
metadata: 
  name: tickets-client-service-cip
spec:
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
